config/redmine_issue_required_repos.yaml

Since its doing strict string checking, need the organization to be capitalized to match.

Update and add Katello repositories

---

.gitignore
.openshift/cron/weekly/close_inactive
config/close_inactive.yaml
scripts/close_inactive.rb

Closes inactive PRs without any update for more than 6 months, sets Inactive
label.

Added close_inactive weekly script

---

config/redmine_issue_required_repos.yaml

Add openscap plugins to the list

---

config/users.yaml

Add akofink and zhunting to users.yaml

---

config/repos.yaml

Added discovery link_to_redmine config

---

app.rb
github/pull_request.rb
scripts/close_inactive.rb
test/github/pull_request_test.rb

Skip commit style checks for WIP PRs

---

app.rb
github/pull_request.rb

This removes the Not yet reviewed and Needs re-review labels if a PR is approved.
Untested because I'm not sure how to test it.

Remove labels on approved review

---

app.rb
config/repos.yaml
github/pull_request.rb
repository.rb

This won't be very useful until https://github.com/theforeman/community-templates/pull/344 is merged.

Set community-template specific labels

---

app.rb
config/repos.yaml
github/pull_request.rb
repository.rb
test/github/pull_request_test.rb

This automatically sets DEB/RPM label on foreman-packaging.

Set labels based on target branches

---

config/repos.yaml

This plugin has been archived.

Remove foreman_host_rundeck

---

config/repos.yaml

Matches https://github.com/theforeman/foreman-infra/pull/617

Remove the PR scanner from plugin repositories

---

config/repos.yaml

this goes along with theforeman/foreman-infra#611

remove smart-proxy and plugins from pr scanning

---

Gemfile
Gemfile.lock
app.rb
config.ru

Add Sentry support

---

app.rb
redmine/issue.rb

The release field is no more. It has ceased to be.

Remove the release handling for Katello

---

github/pull_request.rb

The labeling code had an issue where it compared label names to label objects. This resulted in labels being applied twice. This code should also do fewer API requests.

Clean up label handling code

---

config/repos.yaml

This will mark changes in `assets/javascripts` so tracking/filtering would be easier.

Add legacy js tag for changes in assets/javascripts

---

config/close_inactive.yaml

Looks like a lot of them will get closed.

Shorten closing period for inactive PRs

---

config/repos.yaml

This adds few more labels. Templates are definitely useful, the others are just a proposal.

Adds Templates label and few more

---

config/repos.yaml

Add foreman_statistics repo

---

config/repos.yaml

Added foreman_webhooks RM

---

prprocessor/config/repos.yaml

the repo is archived since 4 years

drop bastion
