- Gemfile
- Gemfile.lock
- github/pull_request.rb
The GitHub API appears to return a 404 sometimes when retrieving
commits for a newly created PR, so retry a few times.
Fixes #33
> Retry retrieval of PR commits

- github/pull_request.rb
Looks like when a line is exactly 72 characters, we get an error:
https://github.com/theforeman/foreman/pull/3491
> Remove CR when checking for line length

- github/pull_request.rb
Prevents warning on a commit message such as:
<pre>
Rails source where relative controller is assumed by url_for if no named
route was given (the :use_route option):
https://github.com/rails/rails/blob/v4.2.6/actionpack/lib/action_dispatch/routing/route_set.rb#L695-L698
</pre>
I think this is quite reasonable and better than using a URL shortener as it's a permanent URL that avoids a dependency on both a shortener service and even GitHub - it's quite usable if you even had a copy of the Rails release or repo with the data in the URL.
(https://github.com/theforeman/foreman/pull/3564#issuecomment-223237738)
> Ignore URLs in commit message line lengths

- app.rb
- redmine/issue.rb
- redmine/project.rb
- redmine/redmine_resource.rb
Katello projects in Redmine use empty release to indicate untriaged
issues, when pull requests are opened or closed and the release is
set to our backlog we want these to moved to untriaged. That ensures
that these issues get consideration during triage sessions for
release parsing.
> For Katello pull requests set release to untriaged

- config/repos.yaml
once https://github.com/theforeman/foreman-infra/pull/268 and this is merged, I'd like to ask @domcleal or @ohadlevy to 
* add PrProcessor webhook to  smart_proxy_openscap GitHub repo
* add the  smart_proxy_openscap repo to the Bots team with write access
as far as I understood from http://projects.theforeman.org/projects/foreman/wiki/Jenkins#Adding-a-new-smart-proxy-plugin only org admins can do it
> Add PR processor to smart_proxy_openscap

- app.rb
- config/repos.yaml
- github/pull_request.rb
- repository.rb
as a comment on a new PR
Open to discussion!
> Add links to the referenced/fixed issues

- config/repos.yaml
it doesn't make much sense to have it under remote execution now
> Move smart_proxy_dynflow under foreman-tasks project

- config/repos.yaml
This now matches [modulesyncs managed_modules.yaml](https://github.com/Katello/foreman-installer-modulesync/blob/master/managed_modules.yml)
> Handle all katello puppet repositories

- github/pull_request.rb
fe16b84b3a033fd860f3859d4aedba90b9e3bf1a caused a regression where the @client propery was no longer set.
> Set the client propery

- scripts/add_webhook.sh
When adding a webhook to foreman_maintain recently, I struggled to get this to work without an OAuth token. GitHub's docs suggest the best way to use such a token is via a curl header (https://developer.github.com/v3/guides/getting-started/#oauth) so I added this as an environment variable to the script
> Add use of OAuth token for running the add_webhook script

- redmine/issue.rb
Some projects do not have the custom field pull_requests so nil is returned. This now handles it for both add and remove.
> Handle projects without the custom field for PRs

- github/pull_request.rb
1ea8acb1ca8dc9087111d1d1d0baf2d256bf30a2 added branch labels, but this ignored any labels that were already present.
The annoying current behavior can be seen in https://github.com/theforeman/foreman-packaging/pull/2201
> Only add branch labels if they're new

- app.rb
I saw an error in production that wasn't helpful:
```
App 6108 stderr: 2018-05-04 16:07:33 - RuntimeError - repo not configured:
```
> Add more debug info on unconfigured repos

- config/repos.yaml
ping @iNecas I found myself wanting this. If you don't I'm also okay without it, I guessed it wasn't added in 6bc2a67b4f4d34bfc4dd16819f283469d6f0c007 because it wasn't documented?
> enable link_to_redmine for foreman_maintain

- app.rb
This was used by the pr scanner to run tests, but since
7b39c36f11474fa6270f935c19423f240a024d9f we no longer use this.
> Remove exception for [test]

- github/pull_request.rb
The previous patch was checking the committer's email address, but it should
have been the author's address.
This patch changes committer to author.
> Fixes #107 - use author, not committer

- app.rb
- redmine/issue.rb
Issue has no id. This adds a string representation so we also know in
which project it is.
> Add a issue string representation

- config/repos.yaml
To make it easy for the UI team to filter pull requests that change the UI, a label is required.
Since most of the UI base code is placed in "webpack" any change to the webpack directory will add the "ui" label to the PR.
//cc @ohadlevy @ares @waldenraines @tbrisker
> Add ui label to any change at webpack in Foreman

- scripts/close_inactive.rb
* Require raven for error reporting
* Only output when there's something to close
* Move the close prs definition to the top
> Fixes for the close inactive script

- config/repos.yaml
There are 2 ideas here:
* A label per release (1.18, 1.19)
* A generic Cherry pick label for all stable branches
Note that these labels currently don't actually exist so this should not be merged. I'm looking for opinions
cc @tbrisker
> [RFC] Add Foreman Branch labels

- app.rb
- config/repos.yaml
- github/pull_request.rb
- repository.rb
- test/config_test.rb
- test/github/pull_request_test.rb
**NOTE**: this is an idea that I have to support [this usecase](https://github.com/theforeman/prprocessor/pull/118#discussion_r211153786). I would love to hear what you think.
Currently you can set labels according to one of the root directories (`app`, `webpack`, etc). In other words, you cannot label a PR according to a file in `app/assets`.
This commit adds this feature. For example in `repos.yml`:
```yml
theforeman/foreman:
directory_labels:
app/assets: ui
app/controllers: backend
webpack: ui
```
it will add `ui` label if there were changed files in `./app/assets/` or `./webpack/` and `backend` label if
a file was changed in `./app/controllers`.
//cc : @ekohl  @ohadlevy  @tbrisker
> Map label to PR according to nested path

- github/pull_request.rb
This comes from a community discussion around prprocesssor
line length restrictions.
https://community.theforeman.org/t/loosen-up-the-commit-line-length-restrictions/12934
It was suggested to keep the commit title length restriction the same and
remove the commit body restrictions
> Remove commit body line length restrictions

- README.md
- prprocessor/__main__.py
- prprocessor/config/repos.yaml
- prprocessor/redmine.py
Replacement of https://github.com/theforeman/prprocessor/pull/106. Still untested and needs code to authenticate against Redmine.
> Set fixed in when a PR is merged

- app.rb
6877213ef97781fe6c8ece188d17b6798f6bbb51 removed the wip? method but failed to remove all callers. This completes that part.
> Complete WIP check removal

- app.rb
- github/pull_request.rb
The new bot can do this and there's no need to duplicate.
> Stop setting a Github status

- config/repos.yaml
https://github.com/Katello/smart_proxy_container_gateway
This is an in-development smart proxy plugin that will allow users to use `podman` with Pulp 3-enabled smart proxies.
> Add smart_proxy_container_gateway smart proxy plugin

- prprocessor/__main__.py
- prprocessor/compat.py
- prprocessor/redmine.py
- setup.py
On OpenShift there's an easy Python 3.8 s2i container but no Python 3.9 version. There is very little code which actually needs 3.9 so reverting this is easier than finding some 3.9 container.
This reverts commits 42b32f6984cc97ca4ff5638a23949d5de2165ed3 and fa5b5d17873653ba356c9f1b6b3c2eb780ad49e6 while also fixing 7e59d7d4c025a6854483cfbc5bbdbd46b3f22361 to be Python < 3.9 compatible again.
> Reintroduce Python 3.7 compatibility

- app.rb
People don't use this label so it just gets applied everywhere. In the [RFC](https://community.theforeman.org/t/drop-needs-testing-label-in-prs/22504) it was agreed to drop the label.
> Stop applying Needs testing label

- prprocessor/__main__.py
Katello follows the convention of using KATELLO- branch prefixes for stable branches, where Foreman uses -stable branch suffixes. This allows the PR processor to set the correct Fixed in releases values for Katello stable branches.
> Add handling of KATELLO- stable branches
